In [1]:
import sys
print(sys.version)

3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]


# Arithmetic

In [9]:
#addition, substraction, multiplication
print(2+3, 2-3, 2*3)

5 -1 6


In [10]:
#division
print(3/2)

1.5


In [11]:
#floor division
print(3//2)

1


In [12]:
#modulo 
print(5%2)

1


In [13]:
#powers 
print(2**3)

8


### exercise: Find the value of $\sqrt{10(\frac{1}{2}+3)}$

In [14]:
#type here


5.916079783099616

# Assignment
The names you use when creating these labels need to follow a few rules:

1. Names can not start with a number.
2. There can be no spaces in the name, use _ instead.
3. Can't use any of these symbols :'",<>/?|\()!@#$%^&*~-+
4. It's considered best practice (PEP8) that names are lowercase.
5. Avoid using the characters 'l' (lowercase letter el), 'O' (uppercase letter oh), 
   or 'I' (uppercase letter eye) as single character variable names.
6. Avoid using words that have special meaning in Python like "list" and "str"


In [ ]:
#code source: Datta Sainath

x = 'Hello' # Assigning a value to a variable
y = 1 # Dynamic typing means that you don't need to declare in advance the type the variable will have

# But once assigned, the variable will be associated with a certain object type 
# as long as the value remains of that type
print(x, type(x))

x += ' World'
print(x, type(x))

x = y
print(x, type(x))
print(y, type(y))

In [ ]:
t = True
f = False
print(type(t))

In [25]:
s = "hello"
dir(s)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',
 'zfill']

In [39]:
print(s.capitalize())  # Capitalize a string; prints "Hello"
print(s.upper())       # Convert a string to uppercase; prints "HELLO"
print(s.rjust(7))      # Right-justify a string, padding with spaces; prints "  hello"
print(s.center(7))     # Center a string, padding with spaces; prints " hello "
print(s.replace('l', '(ell)'))  # Replace all instances of one substring with another;
                                # prints "he(ell)(ell)o"
    
#the above manipulations does not change variable s
print(s)

Hello
HELLO
  hello
 hello 
he(ell)(ell)o
hello


In [40]:
print('  world '.strip())  # Strip leading and trailing whitespace; prints "world"

world


In [59]:
#list

a_list = ['hello', 'I', 'am', 'happy']
b_list = a_list
print(id(a_list), id(b_list))

4430170120 4430170120


In [60]:
#Python is zero index
print(a_list[3])

b_list[3] = 'sad'

print(' a_list is: ', a_list, '\n', 
      'b_list is: ', b_list)

happy
 a_list is:  ['hello', 'I', 'am', 'sad'] 
 b_list is:  ['hello', 'I', 'am', 'sad']


In [61]:
c_list = a_list.copy()

#type here to change c_list[3] to 'gorgeous'

c_list[3] = 'gorgeous'

#print a_list and c_list

print(a_list)
print(c_list)

['hello', 'I', 'am', 'sad']
['hello', 'I', 'am', 'gorgeous']


In [62]:
#dictionary
colors = {'sky':'blue', 'leaves': 'green'}

print(type(colors))
print(colors['sky'])

<class 'dict'>
blue


In [63]:
#add new key-value pairs
colors['roses'] = ['red', 'pink', 'white']

print(colors)

{'sky': 'blue', 'leaves': 'green', 'roses': ['red', 'pink', 'white']}


In [64]:
#loops
print(colors['roses'])

for rose_colors in colors['roses']:
    print(rose_colors)

['red', 'pink', 'white']
red
pink
white


In [71]:
#print formatting

print('sky is {color_sky}, leaves are {color_leaves}'.format(color_sky = colors['sky'], color_leaves = colors['leaves']))

print('sky is {sky}, leaves are {leaves}'.format(**colors))

sky is blue, leaves are green
sky is blue, leaves are green


In [81]:
#functions

def meal_expense(meal_cost, tip = True):
    if tip:
        return meal_cost * 1.15
    else:
        return meal_cost

In [82]:
meal_expense(200)

229.99999999999997

In [85]:
#exercise: rewrite the function so that you can decide the percentage of tips

def meal_expense2(meal_cost, tip=True, tipPercent):
    

In [86]:
meal_expense2(200, 18)

236.0

# Numpy

In [2]:
import numpy as np

In [93]:
a = np.array([1,2,3])
print(a, a.shape)

b = np.array([[1,2,3],[4,5,6]])
print(b, b.shape)

c = np.arange(16).reshape(4, 4)
print(c, c.shape)

[1 2 3] (3,)
[[1 2 3]
 [4 5 6]] (2, 3)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] (4, 4)


In [4]:
print(np.arange(3))

[0 1 2]


In [94]:
#element-wise multiplication
a * 2

array([2, 4, 6])

In [95]:
#matrix multiplication
b.dot(a)

array([14, 32])

In [98]:
dir(a)

In [102]:
print(np.ones((3,3)))
print(np.zeros((3,3)))
print(np.identity(3)) #identity matrix
print(np.diag((1,2,3))) #diagonal matrix
print(np.random.rand(3,3)) #unif(0,1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[0.5012722  0.80913084 0.40294522]
 [0.72784346 0.29595065 0.77313756]
 [0.8991684  0.46509953 0.17839284]]


In [108]:
#array slicing
print(c, '\n')
print(c[:,2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

[ 2  6 10 14]


In [111]:
two_multiples = (c % 2 ==0)
c[two_multiples] = 100
c

array([[100,   1, 100,   3],
       [100,   5, 100,   7],
       [100,   9, 100,  11],
       [100,  13, 100,  15]])

In [109]:
#ravel
c.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

### More numpy exercise: https://www.machinelearningplus.com/python/101-numpy-exercises-python/